backend:
  name: github
  repo: Thyregod/jesperdamgaard.dk
  branch: main

media_folder: public/img
public_folder: img

collections:
  - name: pages
    label: Pages
    files:
      - label: Home
        name: home
        file: content/pages/home.md
        fields:
          - label: Typewriter texts
            name: typewriterTexts
            widget: list
          - label: LinkedIn href
            name: linkedInHref
            widget: string
